vich_uploader:
    twig: false
    form: false
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        measurement:
            uri_prefix: /measurements
            upload_destination: '%kernel.project_dir%/public/measurements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
