version: '3'

x-db: &sql-db-base
  image: postgres:14-alpine
  restart: always
  environment:
    - POSTGRES_USER=ufodata
    - POSTGRES_DB=ufodata
    - POSTGRES_PASSWORD=password

x-app: &app-base
  build:
    context: .
    dockerfile: ./docker/app/Dockerfile
  volumes:
    - ./:/var/www/html/
  environment:
    - APP_SECRET=473e07c3aad5e01e4716fc6860eda710
    - APP_DEBUG=1
    - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
    - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
    - JWT_PASSPHRASE=0df88bf33543f5d6886dc4a538c8b07e
    - MONGODB_DB=measurements
    - FROM_EMAIL_ADDRESS=noreply@ufodata.com

services:
  app:
    <<: *app-base
    container_name: ufodata.app
    environment:
      - APP_ENV=dev
      - POSTGRES_HOST=sql-db
      - POSTGRES_USER=ufodata
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ufodata
      - POSTGRES_PASSWORD=password
      - MAILER_DSN=smtp://mailer:1025
      - USER_ACTIVATION_LINK_URL=http://0.0.0.0:88/api/users/activate/%s
    depends_on:
      - sql-db

  app-test:
    <<: *app-base
    container_name: ufodata.app-test
    environment:
      - APP_ENV=test
      - POSTGRES_HOST=sql-db-test
      - POSTGRES_USER=ufodata
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ufodata
      - POSTGRES_PASSWORD=password
    depends_on:
      - sql-db-test

  sql-db:
    <<: *sql-db-base
    container_name: ufodata.sql-db
    volumes:
      - ufodata-sql-db:/var/lib/postgresql/data

  sql-db-test:
    <<: *sql-db-base
    container_name: ufodata.sql-db-test

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
###< symfony/mailer ###

volumes:
  ufodata-sql-db: ~
